### ISSUE TITLE
Can send multiple MAX_STREAMS with Maximum Stream Identifier 0 value?

### ISSUE THREAD

**Issue by LPardue** [martinthomson/h2-stream-limits#3]
> Endpoints can only increase the value that they include in a MAX_STREAMS frame. An endpoint MUST treat receipt of a Maximum Stream Identifier that is equal to or smaller than a value that it has previously received as a connection error of type PROTOCOL_ERROR; see [Section 5.4.1](https://rfc-editor.org/rfc/rfc9113#section-5.4.1) of [[HTTP/2](https://github.com/martinthomson/h2-stream-limits/issues/new#RFC9113)]. Note that a value of 0, which can be used to indicate support for this feature (see [Section 3.2](https://github.com/martinthomson/h2-stream-limits/issues/new#negotiating)) without permitting the creation of streams, is permitted for both client and server.

The exception might allow an endpoint to send multiple MAX_STREAMS with 0, which is pointless but might be spammable. 

Suggest we tighten the exception to allow only 1 instance of  0 MAX_STREAMS frame in a connection.

**Comment by martinthomson** [comment]
That was my intent: the note says that you can go from max = unknown to max = 0.  That should only happen once though.  I'll try to clarify.
